### ISSUE TITLE
How to deal with `hasChildNodes` of null error?

### ISSUE THREAD

**Issue by sarni-97** [jackdbd/react-neovis-example#1] opened 2019-07-19 04:52 UTC
Hi @jackdbd ,

I tried playing around with the example, but the problem is `this.viz.render()` will fetch the data and try to load onto the dom. But the dom will already execute and it will not wait for the `this.viz.render()` to finish. I'm not quite sure how it worked for you.  Please let me know. I'm attaching a screen shot for reference. 

![neograph](https://user-images.githubusercontent.com/20821482/61510090-4f343e80-a9a6-11e9-8076-01be578d3fe8.JPG)

Thanks,
Sai.

**Comment by jackdbd** [comment] 2019-07-23 21:26
Thanks @sai-velamuri. This repo was just a quick experiment I made to play around with Neo4J, but I want to revamp it in a couple of weeks. Please note this comment I wrote:

https://github.com/jackdbd/react-neovis-example/blob/0dc76b8595d251cc09bd9bad455d9f7ae2047375/src/components/NeoGraph.js#L35

This is no longer true, because the neovis package is now [published on npm](https://www.npmjs.com/package/neovis.js). Probably the author of neovis made some changes and I need to update this application.

**Comment by teenkevo** [comment] 2020-07-14 00:02
On reproducing this example in my own components, I run into a 'TypeError: n is not a function'. Absolutely no idea why I have done everything exactly as you did. 
![Annotation 2020-07-14 080235](https://user-images.githubusercontent.com/46814008/87365278-694c3100-c5a8-11ea-98c0-22839b86fe78.png)

**Comment by jackdbd** [comment] 2020-08-20 08:25
The issue was fixed in #3

**Closed as completed by jackdbd** 2020-08-20 08:25 UTC
